language: java
sudo: false
dist: trusty
install: true
addons:
  sonarcloud:
    organization: "idga-github"
    token:
      secure: "3f5dbb7d5a7cfee2ef984f0ea77bb77b05df052c"
jdk:
   - oraclejdk9
script:
# the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
#JaCoCo is used to have code coverage, the agent has to be activated
  - mvn clean test org.jacoco:jacoco-maven-plugin:prepare-agent package javadoc:javadoc sonar:sonar
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
notifications:
  email: 
  recipients:
    - alu0100979602@ull.edu.es
on_success: always
on_failure: always
